### ISSUE TITLE
API not accessible from outside of localhost

### ISSUE THREAD

**Issue by delatbabel** [devinivy/hapipal-realworld-example-app#13]
Hi -- just a suggestion, given the type of system that this is (back end), it's a bit inconvenient that the API is not accessible from outside of localhost. It took me a while to figure out how to change this (it's the host: 'localhost' line in server/manifest.js). For those of us who are less familiar with HAPI it might be a good idea to document this in the README.md file including how to change it.

**Comment by devinivy** [comment]
Great idea, I can see how could could have been confusing.  Will happily accept a PR for this 👍

**Comment by delatbabel** [comment]
PR sent

**Comment by devinivy** [comment]
Sorry for the wait and thanks for the contribution!
